<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->getTabTitle(); ?></h4>
    </div>
    <div class="fieldset fieldset-wide">
        <b>Transaction Id</b> : <?php echo $this->getOrder_TransactionId(); ?> <br>        
        <div><div id="sales_order_view_tabs_adminhtml_order_view_tab_query_val"></div></div>        
        <input class="scalable go" type="button" name="button" id="button" value=" Verify " onclick="<?php echo $this->getonclick(); ?>" />
    </div>

</div>
